export const posts = [
  {
    slug: "welcome-to-the-iron-psalm-blog",
    title: "Welcome to the Iron Psalm Dev Blog",
    date: "2025-07-01",
    excerpt:
      "Introducing our new development blog where we share progress, features, and musings from behind the scenes.",
    content: `
Iron Psalm has grown from a weekend prototype into a sprawling realm stitched together by code, caffeine, and far-too-many sticky notes.
With this blog we want to lift the hood and show you what's humming underneath: design notes, balance changes, concept art, and the odd poem that fell out of the lore vault.

Over the coming weeks you can expect deep-dives on the action-point system, AI-assisted lore generation, and the cursed bug that once turned every villager into a turnip. Stay tuned — and thank you for journeying with us.

---

— The Development Team
    `,
  },
  {
    slug: "behind-the-scenes-concept-art",
    title: "Behind the Scenes: Concept Art Process",
    date: "2025-07-02",
    excerpt: "A peek into how we develop the visual identity of Iron Psalm's dark fantasy world.",
    content: `
Creating the visual identity for Iron Psalm has been a journey through shadow and light. Every piece of concept art starts with a simple question: what does this place feel like?

Our process begins with rough sketches, often just a few lines that capture the essence of a location. The village, for instance, started as nothing more than a collection of rooftops against a mountain backdrop.

![Early village sketch](/village.png)

From there, we layer in the details that make each location unique. The monastery's spires weren't always so imposing - they grew organically from the need to feel both welcoming and intimidating.

![Monastery development](/monastary.png)

The final pieces often surprise us. What began as simple architectural studies become living, breathing spaces that players will inhabit for hours.

![Final monastery concept](/inner_monastary.png)

This iterative process ensures that every visual element serves the story we're telling. Nothing is arbitrary in Iron Psalm's world.

---

— The Development Team
    `,
  },
  {
    slug: "the-living-world-autonomous-npcs",
    title: "The Living World: Our Roadmap for Autonomous NPCs",
    date: "2025-08-01",
    excerpt: "Our vision for moving beyond scripted characters to a truly simulated society where NPCs have real goals, memories, and consequences.",
    content: `
We're building the core tech that will make our world truly unique, and today we're sharing the plan for our NPCs.

Our vision is simple: **move beyond scripted characters to a Simulated Society.**

![Blacksmith at work](/blacksmith.png)

## Our Philosophy: Simulate Consequences, Not Minutiae

We're skipping trivial needs like hunger. Instead, we're simulating what really drives a society: **resources, relationships, and ambition.** 

An NPC's problem won't be "I'm hungry," it will be "I'm a blacksmith, but I'm out of ore and can't afford more. My business is failing."

This creates problems you can actually interact with.

## The Plan: From a Seed to a Society

We're evolving our NPCs in four key phases.

### Phase 1: The Economic Agent

The first step is a working NPC driven by their job. A blacksmith will work at his forge when he has materials and travel to the mine when he's out. This proves the core AI loop works.

### Phase 2: The Remembering & Social Agent

Next, we give NPCs a real memory. They will remember your actions—good and bad. Helping them will build trust; betraying them will create a grudge. These memories will change how they talk to you and treat you. This also introduces social needs, causing NPCs to gather in places like taverns.

### Phase 3: The Purposeful Agent & Emergent Quests

NPCs will get long-term goals and generate their own daily plans. They'll follow schedules, creating a world that feels purposeful. This is also where emergent quests are born. If our blacksmith can't afford ore, his new goal becomes "find a way to make money." He might then ask you for a loan or offer you a job—a quest generated by the simulation, not a designer.

### Phase 4: A Fully Sovereign Society

Finally, we give NPCs full autonomy. They will earn and spend money, own property, and form their own relationships and rivalries. The world will run on its own, a complex society that you, the player, can influence, disrupt, and explore.

---

This is a huge undertaking, and we'll be rolling these features out over time. Your feedback is crucial as we build a world that truly feels alive.

Thanks for being on this journey with us.

— The Development Team
    `,
  },
];